version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    networks:
      carNET:
  postgresqldb:
    image: postgres
  #  ports:
  #    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=firstproject
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      carNET:


volumes:
    dbdata:
networks:
    carNET: